# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-06 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='review',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
